arch:
  - arm64
os:
  - linux
services:
  - docker
before_install:
  - docker login -u "$DOCKER_USERNAME" -p $DOCKER_PASSWORD
script:
  - cd images/broker/alpine/ && build-broker-image.sh 4.5.0
  - cd images/namesrv/alpine/ && build-namesrv-image.sh 4.5.0
