language: go
go:
- "1.13"
arch:
  - arm64
os:
  - linux
services:
  - docker
before_install:
  - curl -LO https://github.com/operator-framework/operator-sdk/releases/download/v0.18.1/operator-sdk-v0.18.1-aarch64-linux-gnu
  - chmod +x operator-sdk-v0.18.1-aarch64-linux-gnu &&sudo  mv operator-sdk-v0.18.1-aarch64-linux-gnu /usr/local/bin/operator-sdk
  - docker login -u "$DOCKER_USERNAME" -p $DOCKER_PASSWORD
  - export GO111MODULE=on
  - export GOPROXY="https://proxy.golang.org,direct"
install: skip
script:
  - ./create-operator.sh
  - export pwd=$PWD && echo $PWD
  - cd ${pwd}/images/broker/alpine/ && build-broker-image.sh 4.5.0
  - cd ${pwd}/images/namesrv/alpine/ && build-namesrv-image.sh 4.5.0
